Repository pre-onboarding-frontend-7-team-3/pre-onboarding-7th-3-1-3, pull requests merged in 2022-11, with the labels that each got.

#1 [ Feat ] develop/moonjeewon
  .env
  .eslintrc.js
  package-lock.json
  package.json
  src/App.tsx
  src/api/client.jsx
  src/components/Header.jsx
  src/components/Layout.jsx
  src/components/Main/SearchForm.jsx
  src/components/Main/SearchItem.jsx
  src/components/Main/SearchItemList.jsx
  src/hooks/useDebounce.js
  src/hooks/useKeyDown.js
  src/hooks/useSearch.js
  src/index.tsx
  src/pages/main.js
  src/store/searchResult.js
  src/store/searchValue.js
  src/store/selectedSearchResultIndex.js
  src/style/GlobalStyle.js
  src/style/Theme.js
  src/utils/checkEngAndNum.js
  src/utils/formatFontWeight.js
Labels: feat

#3 [ Feat ] 검색창 자동완성
  src/components/Main/SearchForm.jsx
  src/hooks/useKeyDown.ts
  src/hooks/useSearch.ts
Labels: feat

#4 [ Refactor ] 영문까지 검색하고 bold 처리, 검색어 없음 표시
  src/App.tsx
  src/apis/SearchDiseaseService.ts
  src/components/Home/SeachBar/SearchBar.tsx
  src/components/Home/SeachBar/index.js
  src/components/Main/SearchForm.jsx
  src/components/Main/SearchItemList.jsx
  src/hooks/useDebounce.ts
  src/hooks/useKeyDown.ts
  src/hooks/useSearch.ts
  src/pages/Main/main.jsx
  src/pages/Main/main.tsx
  src/utils/checkEngAndNum.js
  src/utils/formatFontWeight.js
  tsconfig.json
Labels: refactor

#5 [ Refactor ] : 변수명 수정 / 구분
  src/components/Main/SearchForm.jsx
Labels: refactor

#6 [ Refactor ] 추천검색어 리스트에 스크롤 생길 시 방향키로 이동가능하도록 구현
  src/components/Main/SearchItem.jsx
  src/components/Main/SearchItemList.jsx
  src/hooks/useKeyDown.ts
Labels: refactor

#9 [FEAT] cache storage통한 캐싱 구현
  package-lock.json
  src/apis/getDataAndRegisterCache.ts
  src/components/Header.tsx
  src/components/Main/FormatFontWeight.jsx
  src/components/Main/SearchForm.tsx
  src/components/Main/SearchItem.tsx
  src/hooks/useSearch.ts
  src/store/searchResult.ts
  src/utils/filterCachedData.ts
  src/utils/formatFontWeight.tsx
  src/utils/getCachedData.ts
  src/utils/makeTrieBySearchWord.ts
Labels: feat

#13 [ Style ] : 컴포넌트 스타일
  .env
  package-lock.json
  package.json
  src/apis/getDataAndRegisterCache.ts
  src/apis/index.ts
  src/components/Header.tsx
  src/components/Main/HighlightedText.tsx
  src/components/Main/SearchItem.tsx
  src/components/Main/SearchItemList.tsx
  src/components/Navbar.tsx
  src/constants/NavData.ts
  src/hooks/useKeyDown.ts
  src/hooks/useSearch.ts
  src/utils/getCachedData.ts
Labels: style

#15 [ Feat ] useScroll hook 분리
  src/components/Main/HighlightedText.tsx
  src/components/Main/SearchItem.tsx
  src/components/Main/SearchItemList.tsx
  src/components/Navbar.tsx
  src/hooks/useKeyDown.ts
  src/hooks/useScroll.ts
  src/hooks/useSearch.ts
  src/utils/checkValidationOfInput.ts
  src/utils/makeTireBySearchWord.ts
Labels: feat, help wanted

#16 [ Docs ] : update README.md
  README.md
Labels: documentation
